### ISSUE TITLE
Use functions with default parameter values.

### ISSUE THREAD

**Issue by KooiInc** [jonrandy/metho#5]
Thanks for this nice repo.

I noticed that `Metho.add` for a function including default parameter functions did not work.

So I forked your repository and created a (slightly refactored) [branch](https://github.com/KooiInc/metho/tree/UseDefaultParams) to enable it. The refactoring meant that you only need the `add` function now.

A few tests can be found in this little [Stackblitz project](https://stackblitz.com/edit/web-platform-atdytt?file=script.js).

Maybe you'll find it useful.

**Comment by jonrandy** [comment]
Thanks, I'll take a look when I have some time

**Comment by jonrandy** [comment]
I took a look at what you did. After some careful consideration, I do feel that this small issue with functions that have a `length` of 0 (due to having default parameters) is better addressed simply by making a note in the documentation.

The `add` function was only added as a convenience method - the other methods are integral parts of Metho. I don't think they should be removed from the export as they provide useful functionality in their own right (safely adding simple properties to objects etc.)

Also, I'm not sure why you would exclude arrow functions from being used? Sure - if you use them, `this` cannot be used - but someone may have a use case for them. I want to keep Metho as open and flexible as possible. Was the problem with arrow functions a consequence of the code you added to check about the default parameters?

**Comment by KooiInc** [comment]
> Also, I'm not sure why you would exclude arrow functions from being used?

I don't see many use cases for it. For extending native Objects you would presumably always like to extend the `prototype`, and use the `this` (instance-) value to do something useful with it. With an arrow function you can just return some value. The charm of your library is that you can do that without the risk of overwriting existing properties/methods.

>  I do feel that this small issue with functions that have a length of 0 (due to having default parameters) is better addressed simply by making a note in the documentation.

That's fine with me ofcourse. I was just a bit annoyed by it trying to use your library.

>  I want to keep Metho as open and flexible as possible

Also fine ofcourse. I keep experimenting [here](https://stackblitz.com/edit/js-t3ushi?file=index.js) (deviced a way to make arrow functions more useful).
